import {
  Armchair,
  Boxes,
  Cable,
  Calendar,
  Camera,
  Crown,
  FileText,
  Flame,
  Guitar,
  Headphones,
  Lightbulb,
  MapPin,
  Mic2,
  Monitor,
  Package,
  Projector,
  Shield,
  Sparkles,
  LayoutGrid,
  Tent,
  Truck,
  Users,
  Volume2,
  Warehouse,
  Wrench,
  Zap,
} from "lucide-react";

const ICONS = {
  volume: Volume2,
  lightbulb: Lightbulb,
  stage: LayoutGrid,
  tent: Tent,
  chair: Armchair,
  monitor: Monitor,
  projector: Projector,
  mic: Mic2,
  zap: Zap,
  cable: Cable,
  sparkles: Sparkles,
  guitar: Guitar,
  camera: Camera,
  package: Package,
  users: Users,
  boxes: Boxes,
  truck: Truck,
  wrench: Wrench,
  file: FileText,
  map: MapPin,
  flame: Flame,
  crown: Crown,
  shield: Shield,
  headphones: Headphones,
  warehouse: Warehouse,
  calendar: Calendar,
};

export function DynamicIcon({ name, size = 22, strokeWidth = 1.75 }) {
  const Icon = ICONS[name] || Package;
  return <Icon size={size} strokeWidth={strokeWidth} aria-hidden />;
}
