import json

# Dữ liệu mẫu — giống mockData.js cũ, nhưng lưu trong Python
CATEGORIES = [
    {"id": 1, "name": "Âm thanh", "icon": "volume"},
    {"id": 2, "name": "Ánh sáng", "icon": "lightbulb"},
    {"id": 3, "name": "Sân khấu", "icon": "stage"},
    {"id": 4, "name": "Nhà bạt", "icon": "tent"},
    {"id": 5, "name": "Bàn ghế", "icon": "chair"},
    {"id": 6, "name": "Màn hình LED", "icon": "monitor"},
    {"id": 7, "name": "Máy chiếu", "icon": "projector"},
    {"id": 8, "name": "Micro & DJ", "icon": "mic"},
    {"id": 9, "name": "Generator", "icon": "zap"},
    {"id": 10, "name": "Dây & Phụ kiện", "icon": "cable"},
    {"id": 11, "name": "Trang trí", "icon": "sparkles"},
    {"id": 12, "name": "Backline", "icon": "guitar"},
    {"id": 13, "name": "Camera live", "icon": "camera"},
    {"id": 14, "name": "Logistics", "icon": "package"},
    {"id": 15, "name": "Nhân sự kỹ thuật", "icon": "users"},
    {"id": 16, "name": "Gói combo", "icon": "boxes"},
]

PRODUCTS = [
    {
        "id": 1,
        "name": "Loa line array 12 inch",
        "description": "Hệ thống loa line array công suất cao, phù hợp sân khấu ngoài trời 500–2000 khách.",
        "price": 850000,
        "original_price": 1200000,
        "discount": 29,
        "sold": 72,
        "stock": 100,
        "rating": 4.8,
        "location": "Hồ Chí Minh",
        "category_id": 1,
        "is_flash": 1,
        "tags": ["loa", "âm thanh", "line array"],
        "image": "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80",
        "specs": ["Công suất 2000W", "Bluetooth/Dante", "Kèm stand"],
    },
    {
        "id": 2,
        "name": "Đèn moving head beam 380",
        "description": "Đèn beam 380W, 16 màu, phù hợp club và sự kiện.",
        "price": 420000,
        "original_price": 580000,
        "discount": 28,
        "sold": 45,
        "stock": 60,
        "rating": 4.7,
        "location": "Hà Nội",
        "category_id": 2,
        "is_flash": 1,
        "tags": ["đèn", "beam", "ánh sáng"],
        "image": "https://images.unsplash.com/photo-1507874457470-272b3c8d8ee2?w=800&q=80",
        "specs": ["380W", "DMX512", "Góc beam 3°"],
    },
    {
        "id": 3,
        "name": "Sân khấu 6x4m gấp",
        "description": "Khung sân khấu nhôm gấp, mặt sàn gỗ chống trượt.",
        "price": 2100000,
        "original_price": 2800000,
        "discount": 25,
        "sold": 18,
        "stock": 30,
        "rating": 4.9,
        "location": "Đà Nẵng",
        "category_id": 3,
        "is_flash": 1,
        "tags": ["sân khấu", "lắp đặt"],
        "image": "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&q=80",
        "specs": ["6x4m", "Tải 500kg/m²", "Kèm lắp đặt"],
    },
    {
        "id": 4,
        "name": "Nhà bạt 10x20m",
        "description": "Nhà bạt khung nhôm, mái PVC chống UV.",
        "price": 3500000,
        "original_price": 4500000,
        "discount": 22,
        "sold": 9,
        "stock": 20,
        "rating": 4.6,
        "location": "Hồ Chí Minh",
        "category_id": 4,
        "is_flash": 1,
        "tags": ["nhà bạt", "wedding", "ngoài trời"],
        "image": "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=800&q=80",
        "specs": ["10x20m", "Chống UV", "Kèm neo"],
    },
    {
        "id": 5,
        "name": "Máy phát điện 20KVA",
        "description": "Máy phát diesel 20KVA, im lặng.",
        "price": 1800000,
        "original_price": 2400000,
        "discount": 25,
        "sold": 31,
        "stock": 50,
        "rating": 4.5,
        "location": "Hà Nội",
        "category_id": 9,
        "is_flash": 1,
        "tags": ["máy phát điện", "generator"],
        "image": "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80",
        "specs": ["20KVA", "Diesel", "Ồn < 75dB"],
    },
    {
        "id": 6,
        "name": "LED wall P3.9 indoor",
        "description": "Màn hình LED trong nhà P3.9, kèm processor.",
        "price": 5200000,
        "original_price": 6800000,
        "discount": 24,
        "sold": 6,
        "stock": 15,
        "rating": 4.9,
        "location": "Hồ Chí Minh",
        "category_id": 6,
        "is_flash": 1,
        "tags": ["led", "màn hình"],
        "image": "https://images.unsplash.com/photo-1598488035139-bdcb86d0b0b2?w=800&q=80",
        "specs": ["P3.9", "Indoor", "Kèm processor"],
    },
    {
        "id": 7,
        "name": "Loa JBL EON 715",
        "description": "Loa active 15 inch, bluetooth.",
        "price": 500000,
        "original_price": 650000,
        "discount": 23,
        "sold": 88,
        "stock": 120,
        "rating": 4.6,
        "location": "Hồ Chí Minh",
        "category_id": 1,
        "is_flash": 0,
        "tags": ["loa", "JBL"],
        "image": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
        "specs": ["15 inch", "1300W", "Bluetooth"],
    },
    {
        "id": 8,
        "name": "Bàn tròn sự kiện + ghế",
        "description": "Combo 10 bàn tròn kèm 80 ghế banquet.",
        "price": 150000,
        "original_price": 200000,
        "discount": 25,
        "sold": 120,
        "stock": 200,
        "rating": 4.4,
        "location": "Đà Nẵng",
        "category_id": 5,
        "is_flash": 0,
        "tags": ["bàn ghế", "wedding"],
        "image": "https://images.unsplash.com/photo-1464366400600-6394ab3a9c32?w=800&q=80",
        "specs": ["10 bàn", "80 ghế", "Kèm phủ"],
    },
    {
        "id": 9,
        "name": "Gói logistics sự kiện 24h",
        "description": "Vận chuyển – lắp đặt – thu hồi trong 24h nội thành HCM.",
        "price": 800000,
        "original_price": 1000000,
        "discount": 20,
        "sold": 55,
        "stock": 80,
        "rating": 4.7,
        "location": "Hồ Chí Minh",
        "category_id": 14,
        "is_flash": 0,
        "tags": ["logistics", "giao hàng", "lắp đặt"],
        "image": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80",
        "specs": ["24h", "Nội thành HCM", "Kèm bảo hiểm"],
    },
    {
        "id": 10,
        "name": "Combo wedding âm thanh + ánh sáng",
        "description": "Trọn gói loa, đèn par, sương khói cho tiệc cưới 200 khách.",
        "price": 4500000,
        "original_price": 6000000,
        "discount": 25,
        "sold": 34,
        "stock": 40,
        "rating": 4.9,
        "location": "Hà Nội",
        "category_id": 16,
        "is_flash": 0,
        "tags": ["combo", "wedding"],
        "image": "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80",
        "specs": ["200 khách", "Kỹ thuật 2 người", "Rehearsal 1 buổi"],
    },
    {
        "id": 11,
        "name": "Máy chiếu 8000 lumens",
        "description": "Máy chiếu Full HD 8000lm, kèm màn 120 inch.",
        "price": 600000,
        "original_price": 800000,
        "discount": 25,
        "sold": 42,
        "stock": 60,
        "rating": 4.5,
        "location": "Hà Nội",
        "category_id": 7,
        "is_flash": 0,
        "tags": ["máy chiếu", "projector"],
        "image": "https://images.unsplash.com/photo-1478720568477-152d9b164e63?w=800&q=80",
        "specs": ["8000lm", "Full HD", "Màn 120 inch"],
    },
    {
        "id": 12,
        "name": "Bộ micro không dây Shure",
        "description": "2 micro cầm + 1 micro cài áo, receiver UHF.",
        "price": 350000,
        "original_price": 450000,
        "discount": 22,
        "sold": 67,
        "stock": 90,
        "rating": 4.8,
        "location": "Hồ Chí Minh",
        "category_id": 8,
        "is_flash": 0,
        "tags": ["micro", "shure"],
        "image": "https://images.unsplash.com/photo-1598488035139-bdcb86d0b0b2?w=800&q=80",
        "specs": ["UHF", "3 micro", "Pin 8h"],
    },
]


def seed_shop_data(db):
    """Nếu chưa có sản phẩm thì thêm dữ liệu mẫu vào database."""
    conn = db.connect()
    count = conn.execute("SELECT COUNT(*) FROM products").fetchone()[0]

    if count > 0:
        conn.close()
        return

    for cat in CATEGORIES:
        conn.execute(
            "INSERT INTO categories (id, name, icon) VALUES (?, ?, ?)",
            (cat["id"], cat["name"], cat["icon"]),
        )

    for p in PRODUCTS:
        conn.execute(
            """
            INSERT INTO products (
                id, name, description, price, original_price, discount,
                sold, stock, rating, location, category_id, is_flash,
                tags, image, specs
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                p["id"],
                p["name"],
                p["description"],
                p["price"],
                p["original_price"],
                p["discount"],
                p["sold"],
                p["stock"],
                p["rating"],
                p["location"],
                p["category_id"],
                p["is_flash"],
                json.dumps(p["tags"], ensure_ascii=False),
                p["image"],
                json.dumps(p["specs"], ensure_ascii=False),
            ),
        )

    conn.commit()
    conn.close()
